version: '3.7'

services:
    postgres:
        image: postgres:11
        restart: always
        container_name: postgres
        environment:
            - POSTGRES_USER=bde_lab_1
            - POSTGRES_PASSWORD=bde_lab_1
            - POSTGRES_DB=postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
    mongo:
        image: mongo:4.2
        restart: "no"
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        volumes:
            - ./data://data/db
        ports:
            - "27017:27017"
