version: '3.7'

services:
    jupyter:
        restart: always
        build:
            context: .
            dockerfile: .Dockerfile
        container_name: jupyter_docker
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=yes
        volumes:
            - ./:/home/jovyan/work
