version: '3.7'

services:
    postgres:
        image: postgres:11
        restart: always
        container_name: postgres
        environment:
            - POSTGRES_USER=bde_lab_5
            - POSTGRES_PASSWORD=bde_lab_5
            - POSTGRES_DB=postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"